---
:ems:
  :ems_nsxt:
    :event_handling:
      :event_groups:
:ems_refresh:
  :nsxt:
    :inventory_object_refresh: true
    :allow_targeted_refresh: true
    :refresh_interval: 4.hours
:http_proxy:
  :nsxt:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_nsxt: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_nsxt_network:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_nsxt_network: {}
